-- drop table if exists entries;
-- create table entries (
--   id integer primary key autoincrement,
--   title text not null,
--   text text not null
-- );

-- drop table if exists messages;
-- create table messages (
--   id integer primary key autoincrement,
--   name text not null,
--   email text not null,
--   message text not null
-- );
